name: Build, test and verify `akka-dev-cert`

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: |
            ~/.m2/repository          

      - name: Configure Maven settings for Akka Secure
        env:
          SECURE_TOKEN: ${{ secrets.SECURE_TOKEN }}
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <profiles>
              <profile>
                <id>akka-profile</id>
                <activation>
                <activeByDefault>true</activeByDefault>
                </activation>
                <repositories>
                    <repository>
                        <id>akka-repository</id>
                        <name>Akka Repository</name>
                        <url>https://repo.akka.io/${SECURE_TOKEN}/secure</url>
                    </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
                <activeProfile>akka-profile</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Build, Test, and Verify
        run: mvn verify
